# 跳过构建在Commit Message中添加 [CI SKIP]
# 192.168.31.5 必须是物理机网卡(可以是虚拟网卡)
kind: pipeline
name: 打包部署[Java-Maven]

clone:
  disable: true

steps:
  - name: 下载源代码[Git]
    image: docker:git
    commands:
      - echo "### $DRONE_GIT_HTTP_URL -> $DRONE_BRANCH"
      - git clone http://172.18.1.1:13000/lizw/clever-security.git ./
      # - git clone $DRONE_GIT_HTTP_URL ./
      - git checkout $DRONE_BRANCH

  - name: 编译源代码[Maven]
    image: maven:3.6.0-jdk-8-alpine
    volumes:
      - name: package-java
        path: /package-java
    commands:
      - mvn package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V -Pprod --settings /package-java/Maven/settings.xml
      # - mvn deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V -Pdev --settings /package-java/Maven/settings.xml
      # - cp -f puli-learn-server/target/puli-learn-server-*-SNAPSHOT.jar /package-java

  - name: 构建镜像[Docker]
    image: plugins/docker:18
    settings:
      # registry: '172.18.1.1:15000'
      repo: '172.18.1.1:15000/java-service/clever-security-server'
      username: lizw
      password: Lizhiwei1993
      # auth: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzc4NTAwMTAsImlhdCI6MTU3NTI1ODAxMCwiaXNzIjoiaGFyYm9yLXRva2VuLWlzc3VlciIsImlkIjoxLCJwaWQiOjQsImFjY2VzcyI6W3siUmVzb3VyY2UiOiIvcHJvamVjdC80L3JlcG9zaXRvcnkiLCJBY3Rpb24iOiJwdXNoIiwiRWZmZWN0IjoiIn1dfQ.RKI2Pzg_lWbUjpVTc3_6-TgSJSWjZZdnmc-yvcM3ONOXxJRcsLYWtWwfav9Q86h52J64Okibncprmj_JcvgayuRFnla1WgFN3jmu6wy_rLfYRAvPEsu9xHIJcwML8MOEtrhtAbbx85ZmHRgK3jkeLBm3weT0Ui56-Z5-iVcUZquNbIlYMWcVA7ykCVUvxmnEoFsjCnrdlRdvQhZMf17Hw0_1iv056qnn-Jv2nlfm_99Idvfnv4APg8q_0bOym8EHdKUM7NkGGd5byKMsJZUwsd4tcvwAn0uu5a2P9zIWxqOd0DpodNTMZMrPeD-l1EWUfhWjBxe_bZ6dSLt6gKIL0pQ2UCUtK65ADk2u0L1-LRimsOeNBxhGyr1MdpGKm8OClgiP6WYinLOJ_JIiesJebpcqD5KRh2XDiDhVRGEMvH97k4tNOPXQ0sq4ZdRGS4a36sopfYgUvmfWUYpRBpmMFZ8A8oqzOncK8yZ7ojRQIJln99tes8dHyFPpm4sLNrAi4chqbwthYIfuyKimx24LtJK8LYXB9NBCF-Jmmg2aBcyTgBOQ7VjvcOT_wR94-6Nra9h3Blpg6EbHFXIJj9ePY4rLLseFbqdeAWO7A7Nsic1p2K5OR03BWb_hEDcw9YVDVMtfweuHGQFy6UpUzQl0yeZGesAz_UFYGTywJ_6RIv4'
      # bip: true
      insecure: true
      dockerfile: ./Dockerfile
      target: prod
      tags: ['0.0.1-SNAPSHOT']
      force_tag: true
      auto_tag: false
      auto_tag_suffix: ''

  - name: 启动Docker容器[SSH]
    image: appleboy/drone-ssh
    settings:
      host: 172.18.1.1
      port: 22
      username:
        from_secret: sshUsername
      password:
        from_secret: sshPassword
      # secrets: [ ssh_username, ssh_password ]
      command_timeout: 300s
      script:
        #- export PATH=$PATH:/Applications/Docker.app/Contents/Resources/bin
        #- echo $PATH
        - echo "------------------< 停止容器 >------------------"
        - docker stop clever-security-server
        - echo "------------------< 删除容器 >------------------"
        - docker rm -v clever-security-server
        - echo "------------------< 删除旧镜像 >------------------"
        - docker rmi 172.18.1.1:15000/java-service/clever-security-server:0.0.1-SNAPSHOT
        - echo "------------------< 拉取新镜像 >------------------"
        - docker pull 172.18.1.1:15000/java-service/clever-security-server:0.0.1-SNAPSHOT
        - echo "------------------< 运行新镜像 >------------------"
        - docker run --name clever-security-server -p 28081:9066 -v /home/lizw/Desktop/docker-opt/logs/java-service:/logs -d 172.18.1.1:15000/java-service/clever-security-server:0.0.1-SNAPSHOT
        - exit

  - name: 发送通知[Email]
    image: drillster/drone-email
    # detach: true
    commands:
      - date
      - cd /etc
      - cp /share/localtime ./
      - date
      - cd /bin
      - ./drone-email
    volumes:
      - name: share
        path: /share
    settings:
      host: smtp.qq.com
      port: 465
      username:
        from_secret: emailUsername
      password:
        from_secret: emailPassword
      skip_verify: false
      from:
        from_secret: emailUsername
      recipients: [ 'lzw1000000@163.com' ]
      recipients_only: false
      subject: '[#{{build.number}}-{{build.status}}] {{repo.name}}'
      body: 'file:///drone/src/drone-email.html'

volumes:
  # 共享文件
  - name: share
    host:
      path: /home/lizw/Desktop/docker-opt/share
  # Java打包目录
  - name: package-java
    host:
      path: /home/lizw/Desktop/docker-opt/package/java

# -------------------------------------------------------------------------------------------------------------