# 跳过构建在Commit Message中添加 [CI SKIP]
# 192.168.31.5 必须是物理机网卡(可以是虚拟网卡)
kind: pipeline
name: 打包部署[Java-Maven]

clone:
  disable: true

steps:
  - name: 下载源代码[Git]
    image: docker:git
    commands:
      - echo "### $DRONE_GIT_HTTP_URL -> $DRONE_BRANCH"
      - git clone http://172.18.1.1:13000/lizw/clever-security.git ./
      # - git clone $DRONE_GIT_HTTP_URL ./
      - git checkout $DRONE_BRANCH

  - name: 编译源代码[Maven]
    image: maven:3.6.0-jdk-8-alpine
    volumes:
      - name: package-java
        path: /package-java
    commands:
      - mvn package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V -Pprod --settings /package-java/Maven/settings.xml
      # - mvn deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V -Pdev --settings /package-java/Maven/settings.xml
      # - cp -f puli-learn-server/target/puli-learn-server-*-SNAPSHOT.jar /package-java

  - name: 构建镜像[Docker]
    image: plugins/docker
    settings:
      registry: 'registry.cn-hangzhou.aliyuncs.com'
      repo: 'registry.cn-hangzhou.aliyuncs.com/msvc/clever-security-server'
      username: lzw1000000@163.com
      password:
        from_secret: harborPassword
      # bip: true
      insecure: true
      dockerfile: ./Dockerfile
      target: prod
      tags: ['1.0.1.RELEASES']
      force_tag: true
      auto_tag: false
      auto_tag_suffix: ''
      debug: true
      launch_debug: true

  - name: 启动Docker容器[SSH]
    image: appleboy/drone-ssh
    settings:
      host: 172.18.1.1
      port: 22
      username:
        from_secret: sshUsername
      password:
        from_secret: sshPassword
      # secrets: [ ssh_username, ssh_password ]
      command_timeout: 300s
      script:
        #- export PATH=$PATH:/Applications/Docker.app/Contents/Resources/bin
        #- echo $PATH
        - echo "------------------< 停止容器 >------------------"
        - docker stop clever-security-server
        - echo "------------------< 删除容器 >------------------"
        - docker rm -v clever-security-server
        - echo "------------------< 删除旧镜像 >------------------"
        - docker rmi registry.cn-hangzhou.aliyuncs.com/msvc/clever-security-server:1.0.1.RELEASES
        - echo "------------------< 拉取新镜像 >------------------"
        - docker pull registry.cn-hangzhou.aliyuncs.com/msvc/clever-security-server:1.0.1.RELEASES
        - echo "------------------< 运行新镜像 >------------------"
        - docker run --name clever-security-server -p 28081:9066 -v /home/lizw/Desktop/docker-opt/logs/java-service:/logs -d registry.cn-hangzhou.aliyuncs.com/msvc/clever-security-server:1.0.1.RELEASES
        - exit

  - name: 发送通知[Email]
    image: drillster/drone-email
    # detach: true
    commands:
      - date
      - cd /etc
      - cp /share/localtime ./
      - date
      - cd /bin
      - ./drone-email
    volumes:
      - name: share
        path: /share
    settings:
      host: smtp.qq.com
      port: 465
      username:
        from_secret: emailUsername
      password:
        from_secret: emailPassword
      skip_verify: false
      from:
        from_secret: emailUsername
      recipients: [ 'lzw1000000@163.com' ]
      recipients_only: false
      subject: '[#{{build.number}}-{{build.status}}] {{repo.name}}'
      body: 'file:///drone/src/drone-email.html'

volumes:
  # 共享文件
  - name: share
    host:
      path: /home/lizw/Desktop/docker-opt/share
  # Java打包目录
  - name: package-java
    host:
      path: /home/lizw/Desktop/docker-opt/package/java

# -------------------------------------------------------------------------------------------------------------